# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pmahele <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/06/13 14:14:03 by pmahele           #+#    #+#              #
#    Updated: 2018/06/13 16:41:39 by pmahele          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = whatever

SRC = whatever.cpp

FLAGS = -Wall -Werror -Wextra

G++ = g++

all = $(NAME)

$(NAME):
	$(G++) $(FLAGS) $(SRC) -o $(NAME)

clean:
	rm -f *.o $(NAME)
